import CoreText
import Foundation
import FoveaCore

/// Registers the bundled feed fonts with Core Text at launch.
///
/// Programmatic registration rather than `ATSApplicationFontsPath`: the Info.plist
/// is generated by `scripts/bundle-app.sh` and only exists inside `build/Fovea.app`,
/// while the normal loop is `swift run Fovea`, which has no plist at all. This path
/// covers both, including `--snapshot` runs.
enum FontRegistry {
    private(set) static var registered: Set<FeedFont> = []
    private(set) static var failures: [(FeedFont, String)] = []

    /// Idempotent: registering the same URL twice is an error Core Text reports,
    /// and the Island panel and the window both come up through here.
    private static var didRun = false

    static func registerAll() {
        guard !didRun else { return }
        didRun = true

        for font in FeedFont.allCases {
            guard let url = FoveaResources.url("Fonts/\(font.file)") else {
                failures.append((font, "not found in the resource bundle"))
                continue
            }
            var error: Unmanaged<CFError>?
            if CTFontManagerRegisterFontsForURL(url as CFURL, .process, &error) {
                registered.insert(font)
            } else {
                let e = error?.takeRetainedValue()
                let code = (e as Error?).map { ($0 as NSError).code } ?? -1
                // kCTFontManagerErrorAlreadyRegistered — fine, the font is usable.
                if code == 105 {
                    registered.insert(font)
                } else {
                    failures.append((font, (e as Error?)?.localizedDescription ?? "unknown error"))
                }
            }
        }

        if !failures.isEmpty {
            // Silent fallback to the system font looks exactly like nothing happened,
            // so say so loudly in the console instead.
            for (font, why) in failures {
                FileHandle.standardError.write(
                    Data("[Fovea] font not registered: \(font.displayName) — \(why)\n".utf8))
            }
        }
    }

    /// Whether a face actually made it in. Views fall back to the system font for
    /// anything that didn't, rather than rendering a wrong family silently.
    static func isAvailable(_ font: FeedFont) -> Bool { registered.contains(font) }
}
